// webappReact/reactapp/src/categoryList.tsx
import React, { Component } from "react";
interface Props {
    selected: string,
    categories: string[],
    selectCategory: (category: string) => void;
}
export class CategoryList extends Component<Props> {
    render() {
        return <div>
            {["All", ...this.props.categories].map(c => {
                let btnClass = this.props.selected === c
                    ? "btn-primary" : "btn-secondary";
                return <button key={c} className={`btn btn-block ${btnClass}`}
                    onClick={() => this.props.selectCategory(c)}>
                    {c}
                </button>
            })}
        </div>
    }
}

// webappAngular/angularapp/src/app/categoryList.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
@Component({
  selector: 'category-list',
  templateUrl: './categoryList.component.html',
})
export class CategegoryList {
  @Input()
  selected: string;
  @Input()
  categories: string[];
  @Output()
  selectCategory = new EventEmitter<string>();
  getBtnClass(category: string): string {
    return (
      'btn btn-block ' +
      (category === this.selected ? 'btn-primary' : 'btn-secondary')
    );
  }
}
