// WebApp/src/header.tsx
import { createElement } from "./tools/jsxFactory";
import { Order } from "./data/entities";
export class Header {
    props: {
        order: Order,
        submitCallback: () => void
    }
    getContent(): HTMLElement {
        let count = this.props.order.productCount;
        return <div className="p-1 bg-secondary text-white text-right">
            {count === 0 ? "(No Selection)"
                : `${count} product(s), $${this.props.order.total.toFixed(2)}`}
            <button className="btn btn-sm btn-primary m-1"
                onclick={this.props.submitCallback}>
                Submit Order            </button>
        </div>
    }
}

// webappvue/vueapp/src/components/Header.vue
<template>
  <div class="p-1 bg-secondary text-white text-right">
    {{ displayText }}
    <router-link to="/order" class="btn btn-sm btn-primary m-1">
            Submit Order
        </router-link>
  </div>
</template>
<script lang="ts">
import { defineComponent, PropType } from "vue";
import { Order } from "../data/entities";
import { useStore } from "vuex";
export default defineComponent({
  name: "Header",
  setup() {
        return { store:  useStore() }
    },
 // props: {
   // order: {
      type: Object as PropType<Order>,
  ////    required: true,
  //  },
  //},
  computed: {
    displayText(): string {
      const count = this.store.state.order.productCount;
      return count === 0
        ? "(No Selection)"
        : `${count} product(s), $${this.store.state.order.total.toFixed(2)}`;
    },
  },
});
</script>
